- name: Install nginx, configure web root folder, deploy custom html page
  hosts: all
  tasks:
  - name: Install nginx web server into Ubuntu ansible nodes
    apt: name=nginx state=latest update_cache=yes

  - name: Start nginx server
    service: name=nginx state=started enabled=true

  - name: Create custom web root folder
    file: path=/var/html state=directory mode=0777

  - name: Configure nginx to use our custom folder while serving html pages
    copy: src=default dest=/etc/nginx/sites-available/default

  - name: Restart nginx service to apply the config changes
    service: name=nginx state=restarted


